### Testar criação de uma tarefa
POST http://localhost:8000/api/tasks/create_one/
Content-Type: application/json

{
  "title": "Nova Tarefa",
  "description": "Descrição da tarefa",
  "completed": false,
  "status": "active"
}

### Testar criação de múltiplas tarefas
POST http://localhost:8000/api/tasks/create_many/
Content-Type: application/json

[
  {
    "title": "Tarefa 1",
    "description": "Descrição 1",
    "completed": false,
    "status": "active"
  },
  {
    "title": "Tarefa 2",
    "description": "Descrição 2",
    "completed": true,
    "status": "inactive"
  }
]

### Testar busca de uma tarefa por ID
GET http://localhost:8000/api/tasks/find_by_id/?id=1

### Testar busca de todas as tarefas
GET http://localhost:8000/api/tasks/find_all/

### Testar busca por um campo específico
GET http://localhost:8000/api/tasks/find_one/?key=title&value=Nova%20Tarefa

### Testar atualização de uma tarefa
PUT http://localhost:8000/api/tasks/update_one/
Content-Type: application/json

{
  "id": 5,
  "title": "Tarefa Atualizada",
  "description": "Descrição atualizada",
  "completed": true,
  "status": "inactive"
}

### Testar atualização de múltiplas tarefas
PUT http://localhost:8000/api/tasks/update_many/
Content-Type: application/json

[
    {
        "id": 7,
        "title": "Tarefa 1 Atualizada",
        "description": "Descrição 1 Atualizada",
        "completed": true,
        "status": "inactive"
    },
    {
        "id": 8,
        "title": "Tarefa 2 Atualizada",
        "description": "Descrição 2 Atualizada",
        "completed": false,
        "status": "active"
    }
]

### Testar remoção de uma tarefa
DELETE http://localhost:8000/api/tasks/remove_one/
Content-Type: application/json

{
  "id": 6
}

### Testar remoção de múltiplas tarefas
DELETE http://localhost:8000/api/tasks/remove_many/
Content-Type: application/json

{
  "ids": [4, 3]
}

### Testar busca com pesquisa por título
GET http://localhost:8000/api/tasks/search/?search=Atua

### Testar busca com filtro por status
GET http://localhost:8000/api/tasks/filter/?status=inactive

### Testar se uma tarefa existe por ID
GET http://localhost:8000/api/tasks/exists_by_id/?id=2